#!/bin/bash

set -xe

dest=$1

input="$(cat)"

repos=$(jq '.source.repos' -r <<< "$input")
git_url=$(jq '.source.git_url' -r <<< "$input")
git_host=$(jq '.source.git_host' -r <<< "$input")
private_key=$(jq '.source.private_key' -r <<< "$input")

eval `ssh-agent`

if [ ! -d $HOME/.ssh ]; then
  mkdir -p $HOME/.ssh
fi

ssh-keyscan $git_host >> ~/.ssh/known_hosts
ssh-add - <<< "$private_key"

git clone ${git_url}/${repos} $dest

echo $repos | xargs -n 1 -P 30 git clone

echo '{ "version": { "ref": "none", "message": "Hello World" }, "metadata": [{ "name": "message", "value": "Hello World" }] }'
