#!/bin/bash

set -xe

dest=$1

input="$(cat)"

repos=$(jq '.source.repos[]' -r <<< "$input")
git_url=$(jq '.source.git_url' -r <<< "$input")
git_host=$(jq '.source.git_host' -r <<< "$input")
private_key=$(jq '.source.private_key' -r <<< "$input")

eval `ssh-agent`

if [ ! -d $HOME/.ssh ]; then
  mkdir -p $HOME/.ssh
fi

ssh-keyscan $git_host >> ~/.ssh/known_hosts
ssh-add - <<< "$private_key"

# printf "$repos" | xargs -P 30 -I % bash -c "git clone $git_url/%.git $dest/%"

# for repo in $repos; do
#     git clone $git_url/$repo.git $dest/$repo
# done

return_ref=none
metadata='[{ "name": "message", "value": "Hello World" }]'

jq -n "{
  version: {ref: $(echo $return_ref | jq -R .)},
  metadata: $metadata
}"