#!/bin/bash

set -xeuf -o pipefail

dest=$1

now=$(date +%s)

input="$(cat)"

repos=$(jq '.source.repos[]' -r <<< "$input")
git_url=$(jq '.source.git_url' -r <<< "$input")
git_host=$(jq '.source.git_host' -r <<< "$input")
private_key=$(jq '.source.private_key' -r <<< "$input")
version=$(jq '.source.version.hash' -r <<< "$input")

eval "$(ssh-agent)" 1> /dev/null

if [ ! -d "$HOME/.ssh" ]; then
  mkdir -p "$HOME/.ssh"
fi

ssh-keyscan "$git_host" >> ~/.ssh/known_hosts
ssh-add - <<< "$private_key"


printf "%s" "$repos" | xargs -P 30 -I % bash -c "git clone $git_url/%.git $dest/%"

printf "%s" "$repos" | xargs -I % sh -c "cd $dest/% && git log | head -1 | cut -d ' ' -f2 >> /tmp/lastcommits_${now}.log"

hash=$(md5sum /tmp/lastcommits_${now}.log | cut -d " " -f1)

jq -n "{
  hash: $(echo "$hash" | jq -R .),
  metadata: [{ name: \"hash\", value: $(echo "$hash" | jq -R .) }]
}"